using System.Text.Json;
using MaintainUk.Api.Application.Services;

namespace MaintainUk.Api.Infrastructure.Services;

/// <summary>
/// Mock AI client that returns deterministic, safe outputs for development and tests.
/// This avoids any dependency on a real LLM or API key.
/// </summary>
public class MockAiClient : IAiClient
{
    public Task<AiResult> ExecuteAsync(
        AiFeatureKey feature,
        string systemPrompt,
        object userPayload,
        CancellationToken cancellationToken = default)
    {
        // We serialize a simple anonymous object for each feature.
        object payload = feature switch
        {
            AiFeatureKey.Intake => new
            {
                category = "General Maintenance",
                urgency = "Routine",
                summary = "Sample issue summary generated by mock AI.",
                missingInfoQuestions = new[]
                {
                    "When did the issue start?",
                    "Can you provide a photo of the affected area?"
                },
                recommendedNextAction = "Review details and schedule a contractor visit."
            },
            AiFeatureKey.QuoteReview => new
            {
                riskFlags = new[] { "Price appears above typical range for this category." },
                suggestedQuestions = new[]
                {
                    "Can you provide a breakdown of labour and materials?",
                    "Are there any exclusions we should be aware of?"
                },
                recommendation = "Review",
                confidence = 0.8m,
                rationale = "Based on typical costs and the information provided."
            },
            AiFeatureKey.CommsDraft => new
            {
                subject = "Update on your maintenance job",
                body = "Hello,\n\nThis is a sample message draft generated by mock AI.\n\nKind regards,\nMaintainUK"
            },
            AiFeatureKey.JobSummary => new
            {
                summary = new[]
                {
                    "Job created and assigned to a contractor.",
                    "Initial inspection completed with photos uploaded."
                },
                openBlockers = new[] { "Awaiting quote approval from organisation admin." },
                nextSteps = new[]
                {
                    "Review and approve the quote.",
                    "Schedule works with the contractor."
                },
                slaRisk = "Low"
            },
            _ => new { message = "Unsupported feature in MockAiClient." }
        };

        var json = JsonSerializer.SerializeToElement(payload);

        // Tokens and confidence are arbitrary in the mock; they just need to be consistent and safe.
        var result = new AiResult(
            Output: json,
            TokensIn: 100,
            TokensOut: 200,
            Confidence: feature == AiFeatureKey.QuoteReview ? 0.8m : 0.9m);

        return Task.FromResult(result);
    }
}

